name: Format
on:
  push:
  workflow_dispatch:

jobs:
  codetest:
    name: Format with black
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        swap-size-mb: 1024
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install poetry
        poetry install --without torch
        poetry add torch --source torch_cpu
    - name: black
      run: |
        poetry run black --check --diff --quiet --skip-magic-trailing-comma .